version: 2
defaults: &defaults
    docker:
      - image: docker:17.11.0-ce-git        
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade 
restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-lsp-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-lsp-{{ checksum "package-lock.json" }}
  paths:
    - node_modules           

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - restore_cache: *restore_cache_settings_for_build
      - run: chmod +x build.sh
      - run: ./build.sh DEV
      - save_cache: *save_cache_settings          
      #add deploy master script here
       
  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - restore_cache: *restore_cache_settings_for_build
      - restore_cache: *restore_cache_settings_for_build
      - run: ./build.sh PROD
      - save_cache: *save_cache_settings        
       
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only:
                - dev-circleci 
                - develop
