version: '3'
services:
  submission-processor:
    image: submission-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    command: npm start
    network_mode: "host"
