version: '3'
services:
  submission-processor:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    command: npm run docker-start
    network_mode: "host"
